from __future__ import annotations

import json
import os
from typing import Any, Optional

from .models import PathwayPlan
from .prompts import (
    STOPFORGREEN_LUNA_SYSTEM_PROMPT,
    build_luna_pathway_prompt,
    pathway_advisor_schema,
)


class LunaAdvisorError(RuntimeError):
    pass


class LunaAdvisor:
    """
    Optional GPT-5.6 Luna advisory layer.

    The simulation planner decides candidate times. Luna can audit/interpret
    only candidates already produced by the planner.
    """

    def __init__(
        self,
        *,
        model: Optional[str] = None,
        reasoning_effort: Optional[str] = None,
    ) -> None:
        self.model = model or os.getenv(
            "STOPFORGREEN_OPENAI_MODEL",
            "gpt-5.6-luna",
        )
        self.reasoning_effort = reasoning_effort or os.getenv(
            "STOPFORGREEN_REASONING_EFFORT",
            "high",
        )

    def _validate_candidate_identity(
        self,
        plan: PathwayPlan,
        data: dict[str, Any],
    ) -> dict[str, Any]:
        allowed = {
            c.candidate_id: c
            for c in (plan.recommended, *plan.alternatives)
        }
        cid = str(data.get("recommended_candidate_id", ""))
        if cid not in allowed:
            raise LunaAdvisorError(
                "Luna selected a departure candidate not generated by the simulator"
            )

        chosen = allowed[cid]
        if data.get("recommended_departure_local") != chosen.departure_local.isoformat():
            raise LunaAdvisorError(
                "Luna changed the timestamp of a simulator-generated candidate"
            )

        # Exact numeric guardrails for the most important fields.
        sched = data.get("schedule_assessment") or {}
        green = data.get("green_pathway_assessment") or {}

        checks = [
            (sched.get("p_arrive_in_window"), chosen.p_arrive_in_window, 0.005),
            (green.get("mean_green_fraction"), chosen.mean_green_fraction, 0.005),
            (
                green.get("p_green_fraction_ge_target"),
                chosen.p_green_fraction_ge_target,
                0.005,
            ),
            (green.get("p_all_green"), chosen.p_all_green, 0.002),
            (green.get("expected_red_stops"), chosen.expected_red_stops, 0.05),
            (
                green.get("median_signal_wait_s"),
                chosen.median_signal_wait_s,
                0.25,
            ),
            (green.get("robustness"), chosen.robustness, 0.005),
        ]
        for observed, expected, tol in checks:
            try:
                if abs(float(observed) - float(expected)) > tol:
                    raise LunaAdvisorError(
                        "Luna altered simulator probabilities/metrics"
                    )
            except (TypeError, ValueError) as exc:
                raise LunaAdvisorError(
                    "Luna returned a non-numeric simulator metric"
                ) from exc

        return data

    def advise(self, plan: PathwayPlan) -> dict[str, Any]:
        try:
            from openai import OpenAI
        except Exception as exc:
            raise LunaAdvisorError(
                "openai package is required for --use-luna"
            ) from exc

        if not os.getenv("OPENAI_API_KEY"):
            raise LunaAdvisorError(
                "OPENAI_API_KEY is not set; simulation result is still available"
            )

        client = OpenAI()
        response = client.responses.create(
            model=self.model,
            reasoning={"effort": self.reasoning_effort},
            instructions=STOPFORGREEN_LUNA_SYSTEM_PROMPT,
            input=build_luna_pathway_prompt(plan),
            text={
                "format": {
                    "type": "json_schema",
                    "name": "stopforgreen_pathway_advice",
                    "strict": True,
                    "schema": pathway_advisor_schema(),
                }
            },
            store=False,
        )

        text = getattr(response, "output_text", "") or ""
        if not text.strip():
            raise LunaAdvisorError("Luna returned no output text")

        try:
            data = json.loads(text)
        except json.JSONDecodeError as exc:
            raise LunaAdvisorError("Luna output was not valid JSON") from exc

        return self._validate_candidate_identity(plan, data)


def deterministic_advice(plan: PathwayPlan) -> dict[str, Any]:
    c = plan.recommended
    return {
        "recommended_candidate_id": c.candidate_id,
        "recommended_departure_local": c.departure_local.isoformat(),
        "summary": (
            "Simulation-selected departure maximizing arrival-window fit and "
            "green-light probability under modeled uncertainty."
        ),
        "schedule_assessment": {
            "p_arrive_in_window": c.p_arrive_in_window,
            "median_arrival_local": c.median_arrival_local.isoformat(),
            "p05_arrival_local": c.p05_arrival_local.isoformat(),
            "p95_arrival_local": c.p95_arrival_local.isoformat(),
        },
        "green_pathway_assessment": {
            "mean_green_fraction": c.mean_green_fraction,
            "p_green_fraction_ge_target": c.p_green_fraction_ge_target,
            "p_all_green": c.p_all_green,
            "expected_red_stops": c.expected_red_stops,
            "median_signal_wait_s": c.median_signal_wait_s,
            "robustness": c.robustness,
        },
        "uncertainty_note": (
            "All signal states are simulated probabilities, not live controller telemetry."
        ),
        "safety_note": (
            "Obey every physical signal and posted traffic law; do not speed to preserve a modeled green wave."
        ),
        "alternative_candidate_ids": [
            x.candidate_id for x in plan.alternatives
        ],
    }
